[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
C = ES
O = company
OU = Linux Software Department
CN = HUB_IP
[v3_req]
keyUsage = digitalSignature, keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
IP_OR_DNS.1 = HUB_IP # this needs an IP alternative name in order to work appropriately with HUB_IP ip name. In a DNS case, this alternative name should be a DNS record
